# -*- coding: utf-8 -*-
"""Temperature convertion (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZA9qlKIh8aiXMNVTT-jqcSZFyHalIHNa
"""

!pip install pint

import pint

ureg = pint.UnitRegistry()

def konversi_jarak():
    kilometer = float(input("Masukkan nilai dalam kilometer: "))
    mil = ureg.Quantity(kilometer, ureg.kilometer).to(ureg.mile)
    print("Nilai dalam mil: ",round(mil.magnitude))

def konversi_suhu():
    celsius = float(input("Masukkan nilai dalam Celsius: "))
    # diubah dari C => F
    fahrenheit = ureg.Quantity(celsius, ureg.degC).to(ureg.degF)
    # diubah dari C => R
    reamur = (4/5) * celsius
    # dibah dari C => K
    kelvin = ureg.Quantity(celsius, ureg.degC).to(ureg.kelvin)

#print hasil ke 3 nya
    print("Nilai dalam Fahrenheit: ", round(fahrenheit.magnitude))
    print("Nilai dalam Reamur: ", round(reamur))
    print("Nilai dalam Kelvin: ", round(kelvin.magnitude))

#Pilihan menu untuk user
print("Pilih jenis konversi yang ingin dilakukan:")
print("1. Konversi jarak (kilometer ke mil)")
print("2. Konversi suhu (Celsius ke Fahrenheit)")

pilihan = int(input("Masukkan pilihan Anda (1 atau 2): "))

if pilihan == 1:
    konversi_jarak()
elif pilihan == 2:
    konversi_suhu()
else:
    print("Pilihan tidak valid")